### PR TITLE
Ask user what kind of role change candidate has done.

### PR DESCRIPTION
**Pull request by mforner13**
Replaced the previous set of radio buttons with 3 detailing each kind of role change you can have and gave the title 'describe the candidate's role change'. Haven't yet changed the back-end to reflect this.

### CODE REVIEW

**Comment by mforner13** [comment]
Merged the code Jonathan wrote today in my local, giving cabinet office an id of 200 after the issue of not adding the organisation to the bottom of the list and numbering it consecutively.

**Comment by mforner13** [comment]
image

Screenshot of new radio buttons to describe candidate's role change.

**Comment by jonodrew** [comment]
Changes look great! We can't merge yet as the frontend changes will break things at the backend, so let's look at that next.

**Comment by jonodrew** [comment]
This should solve #63

**Comment by jonodrew** [comment]
Closing this in favour of https://github.com/jonodrew/talent-tracker/pull/119

@mforner13 thank you for all your hard work on this - it made it super easy to build the frontend!

**Pull request closed without merging**
